import "../styles/modern-normalize.css";
import "../styles/style.css";
import "../styles/components/header.css";
import "../styles/components/mobile-nav.css";
import "../styles/components/hero.css";
import "../styles/components/study.css";
import "../styles/components/about.css";
import "../styles/components/faq.css";
import "../styles/components/testimonials.css";
import "../styles/components/footer.css";
import "../styles/components/pomodoro.css";
import "../styles/utils.css";

import mobileNav from "./utils/mobile-nav";
import siteAnimations from "./utils/animations";
import tabbedComponent from "./utils/tabbed-component";
import lazyLoading from "./utils/lazy-loading";
import accordionComponent from "./utils/accordion";
import sliderComponent from "./utils/slider";
import pomodoroTimer from "./utils/pomodoro";
mobileNav();
siteAnimations();
tabbedComponent();
lazyLoading();
accordionComponent();
sliderComponent();
pomodoroTimer();
